"""Initial schema for QuantFlow with partitioned tables and aggregates.

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-08-22 17:30:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # 1. Enums (PostgreSQL native enums or VARCHAR fallback)
    order_side_enum = sa.Enum(
        "buy", "sell", name="order_side", native_enum=is_postgres
    )
    order_type_enum = sa.Enum(
        "market",
        "limit",
        "stop_loss",
        "take_profit",
        name="order_type",
        native_enum=is_postgres,
    )
    order_status_enum = sa.Enum(
        "pending",
        "open",
        "filled",
        "partially_filled",
        "cancelled",
        "rejected",
        "expired",
        name="order_status",
        native_enum=is_postgres,
    )
    signal_direction_enum = sa.Enum(
        "buy", "sell", "hold", name="signal_direction", native_enum=is_postgres
    )
    log_level_enum = sa.Enum(
        "DEBUG",
        "INFO",
        "WARNING",
        "ERROR",
        "CRITICAL",
        name="log_level",
        native_enum=is_postgres,
    )
    pk_col_type = sa.BigInteger().with_variant(sa.Integer(), "sqlite")

    # 2. Partitioned Tables: Tickers, Orderbooks, Logs, Errors
    if is_postgres:
        # PostgreSQL Range Partitioning DDL
        op.execute(
            """
            CREATE TABLE IF NOT EXISTS tickers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                symbol TEXT NOT NULL,
                bid DECIMAL(20,10) NOT NULL,
                ask DECIMAL(20,10) NOT NULL,
                last DECIMAL(20,10) NOT NULL,
                volume DECIMAL(20,10) NOT NULL,
                timestamp_exchange TIMESTAMPTZ NOT NULL,
                received_at TIMESTAMPTZ NOT NULL,
                source TEXT NOT NULL,
                metadata JSONB DEFAULT '{}',
                PRIMARY KEY (id, received_at)
            ) PARTITION BY RANGE (received_at);
            """
        )
        op.execute(
            "CREATE TABLE IF NOT EXISTS tickers_default "
            "PARTITION OF tickers DEFAULT;"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_tickers_symbol_timestamp "
            "ON tickers (symbol, timestamp_exchange DESC);"
        )

        op.execute(
            """
            CREATE TABLE IF NOT EXISTS orderbooks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                symbol TEXT NOT NULL,
                bids JSONB NOT NULL,
                asks JSONB NOT NULL,
                last_update_id BIGINT,
                timestamp_exchange TIMESTAMPTZ NOT NULL,
                received_at TIMESTAMPTZ NOT NULL,
                source TEXT NOT NULL,
                metadata JSONB DEFAULT '{}',
                PRIMARY KEY (id, received_at)
            ) PARTITION BY RANGE (received_at);
            """
        )
        op.execute(
            "CREATE TABLE IF NOT EXISTS orderbooks_default "
            "PARTITION OF orderbooks DEFAULT;"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_orderbooks_symbol_timestamp "
            "ON orderbooks (symbol, timestamp_exchange DESC);"
        )

        op.execute(
            """
            CREATE TABLE IF NOT EXISTS logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                correlation_id UUID,
                level log_level NOT NULL,
                logger_name TEXT NOT NULL,
                message TEXT NOT NULL,
                metadata JSONB DEFAULT '{}',
                received_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY (id, received_at)
            ) PARTITION BY RANGE (received_at);
            """
        )
        op.execute(
            "CREATE TABLE IF NOT EXISTS logs_default "
            "PARTITION OF logs DEFAULT;"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_logs_correlation_id "
            "ON logs (correlation_id);"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_logs_level ON logs (level);"
        )

        op.execute(
            """
            CREATE TABLE IF NOT EXISTS errors (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                correlation_id UUID,
                error_code TEXT,
                error_message TEXT NOT NULL,
                stack_trace TEXT,
                component TEXT NOT NULL,
                received_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY (id, received_at)
            ) PARTITION BY RANGE (received_at);
            """
        )
        op.execute(
            "CREATE TABLE IF NOT EXISTS errors_default "
            "PARTITION OF errors DEFAULT;"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_errors_component "
            "ON errors (component);"
        )
    else:
        # SQLite / Standard Dialect tables
        op.create_table(
            "tickers",
            sa.Column(
                "id", pk_col_type, primary_key=True, autoincrement=True
            ),
            sa.Column("symbol", sa.String(), nullable=False, index=True),
            sa.Column("bid", sa.DECIMAL(20, 10), nullable=False),
            sa.Column("ask", sa.DECIMAL(20, 10), nullable=False),
            sa.Column("last", sa.DECIMAL(20, 10), nullable=False),
            sa.Column("volume", sa.DECIMAL(20, 10), nullable=False),
            sa.Column(
                "timestamp_exchange", sa.DateTime(timezone=True), nullable=False
            ),
            sa.Column(
                "received_at", sa.DateTime(timezone=True), nullable=False
            ),
            sa.Column("source", sa.String(), nullable=False),
            sa.Column("metadata", sa.JSON(), nullable=True),
        )
        op.create_index(
            "idx_tickers_symbol_timestamp",
            "tickers",
            ["symbol", "timestamp_exchange"],
        )

        op.create_table(
            "orderbooks",
            sa.Column(
                "id", pk_col_type, primary_key=True, autoincrement=True
            ),
            sa.Column("symbol", sa.String(), nullable=False, index=True),
            sa.Column("bids", sa.JSON(), nullable=False),
            sa.Column("asks", sa.JSON(), nullable=False),
            sa.Column("last_update_id", sa.BigInteger(), nullable=True),
            sa.Column(
                "timestamp_exchange", sa.DateTime(timezone=True), nullable=False
            ),
            sa.Column(
                "received_at", sa.DateTime(timezone=True), nullable=False
            ),
            sa.Column("source", sa.String(), nullable=False),
            sa.Column("metadata", sa.JSON(), nullable=True),
        )
        op.create_index(
            "idx_orderbooks_symbol_timestamp",
            "orderbooks",
            ["symbol", "timestamp_exchange"],
        )

        op.create_table(
            "logs",
            sa.Column(
                "id", pk_col_type, primary_key=True, autoincrement=True
            ),
            sa.Column("correlation_id", sa.Uuid(), nullable=True, index=True),
            sa.Column("level", log_level_enum, nullable=False),
            sa.Column("logger_name", sa.String(), nullable=False),
            sa.Column("message", sa.Text(), nullable=False),
            sa.Column("metadata", sa.JSON(), nullable=True),
            sa.Column(
                "received_at", sa.DateTime(timezone=True), nullable=False
            ),
        )
        op.create_index("idx_logs_level", "logs", ["level"])

        op.create_table(
            "errors",
            sa.Column(
                "id", pk_col_type, primary_key=True, autoincrement=True
            ),
            sa.Column("correlation_id", sa.Uuid(), nullable=True),
            sa.Column("error_code", sa.String(), nullable=True),
            sa.Column("error_message", sa.Text(), nullable=False),
            sa.Column("stack_trace", sa.Text(), nullable=True),
            sa.Column("component", sa.String(), nullable=False, index=True),
            sa.Column(
                "received_at", sa.DateTime(timezone=True), nullable=False
            ),
        )

    # 3. Regular Tables
    op.create_table(
        "strategies",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column("name", sa.String(), unique=True, nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "active", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "signals",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column("event_id", sa.Uuid(), unique=True, nullable=False),
        sa.Column(
            "strategy_name",
            sa.String(),
            sa.ForeignKey("strategies.name"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("direction", signal_direction_enum, nullable=False),
        sa.Column("confidence", sa.DECIMAL(5, 4), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "timestamp_exchange", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "received_at", sa.DateTime(timezone=True), nullable=False
        ),
    )
    op.create_index(
        "idx_signals_symbol_timestamp",
        "signals",
        ["symbol", "timestamp_exchange"],
    )
    op.create_index("idx_signals_strategy", "signals", ["strategy_name"])

    op.create_table(
        "orders",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column("order_id", sa.Uuid(), unique=True, nullable=False),
        sa.Column("exchange_order_id", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("side", order_side_enum, nullable=False),
        sa.Column("order_type", order_type_enum, nullable=False),
        sa.Column("quantity", sa.DECIMAL(20, 10), nullable=False),
        sa.Column(
            "filled_quantity",
            sa.DECIMAL(20, 10),
            nullable=False,
            server_default="0",
        ),
        sa.Column("avg_price", sa.DECIMAL(20, 10), nullable=True),
        sa.Column("limit_price", sa.DECIMAL(20, 10), nullable=True),
        sa.Column("stop_price", sa.DECIMAL(20, 10), nullable=True),
        sa.Column(
            "time_in_force", sa.String(), nullable=False, server_default="GTC"
        ),
        sa.Column("status", order_status_enum, nullable=False),
        sa.Column(
            "strategy_name",
            sa.String(),
            sa.ForeignKey("strategies.name"),
            nullable=False,
        ),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("idx_orders_symbol", "orders", ["symbol"])
    op.create_index("idx_orders_status", "orders", ["status"])
    op.create_index("idx_orders_strategy", "orders", ["strategy_name"])

    op.create_table(
        "executions",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column("fill_id", sa.Uuid(), unique=True, nullable=False),
        sa.Column(
            "order_id",
            sa.Uuid(),
            sa.ForeignKey("orders.order_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("side", order_side_enum, nullable=False),
        sa.Column("price", sa.DECIMAL(20, 10), nullable=False),
        sa.Column("quantity", sa.DECIMAL(20, 10), nullable=False),
        sa.Column(
            "commission",
            sa.DECIMAL(20, 10),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "timestamp_exchange", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "received_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("metadata", sa.JSON(), nullable=True),
    )
    op.create_index("idx_executions_order_id", "executions", ["order_id"])
    op.create_index(
        "idx_executions_symbol_timestamp",
        "executions",
        ["symbol", "timestamp_exchange"],
    )

    op.create_table(
        "positions",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column(
            "portfolio_id",
            sa.String(),
            nullable=False,
            server_default="quantflow_main",
        ),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("quantity", sa.DECIMAL(20, 10), nullable=False),
        sa.Column("avg_entry_price", sa.DECIMAL(20, 10), nullable=False),
        sa.Column("unrealized_pnl", sa.DECIMAL(20, 10), nullable=True),
        sa.Column("realized_pnl", sa.DECIMAL(20, 10), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "portfolio_id", "symbol", name="uq_positions_portfolio_symbol"
        ),
    )
    op.create_index(
        "idx_positions_portfolio", "positions", ["portfolio_id"]
    )

    op.create_table(
        "portfolio",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column(
            "portfolio_id",
            sa.String(),
            unique=True,
            nullable=False,
            server_default="quantflow_main",
        ),
        sa.Column("cash", sa.DECIMAL(20, 10), nullable=False),
        sa.Column("total_equity", sa.DECIMAL(20, 10), nullable=False),
        sa.Column("total_exposure", sa.DECIMAL(20, 10), nullable=False),
        sa.Column(
            "realized_pnl",
            sa.DECIMAL(20, 10),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "unrealized_pnl",
            sa.DECIMAL(20, 10),
            nullable=False,
            server_default="0",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("idx_portfolio_id", "portfolio", ["portfolio_id"])

    op.create_table(
        "metrics",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column(
            "portfolio_id",
            sa.String(),
            nullable=False,
            server_default="quantflow_main",
        ),
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("metric_value", sa.DECIMAL(20, 6), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
    )
    op.create_index(
        "idx_metrics_name_timestamp", "metrics", ["metric_name", "timestamp"]
    )

    op.create_table(
        "partition_metadata",
        sa.Column(
            "id", pk_col_type, primary_key=True, autoincrement=True
        ),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("partition_name", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "table_name", "partition_name", name="uq_partition_meta"
        ),
    )


def downgrade() -> None:
    op.drop_table("partition_metadata")
    op.drop_table("metrics")
    op.drop_table("portfolio")
    op.drop_table("positions")
    op.drop_table("executions")
    op.drop_table("orders")
    op.drop_table("signals")
    op.drop_table("strategies")
    op.drop_table("errors")
    op.drop_table("logs")
    op.drop_table("orderbooks")
    op.drop_table("tickers")
